server:
  port: 8083
spring:
  application:
    name: spring-cloud-order-fengin-hystrix8083
#  security:
#    user:
#      name: wangxin
#      password: wangxin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://wangxin:wangxin@localhost:7003/eureka/,http://wangxin:wangxin@localhost:7004/eureka/
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
        timeout:
          enabled: true 
ribbon:
  MaxAutoRetries: 2 
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: false  
  ConnectTimeout: 5000  
  ReadTimeout: 3000 
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

